#ifdef SPANISH
	#define STR0001 "Emision de las solicitudes de compras informadas"
	#define STR0002 "Solicitudes de Compra"
	#define STR0003 "A Rayas"
	#define STR0004 "Administracion"
	#define STR0005 "Ene"
	#define STR0006 "Feb"
	#define STR0007 "Mar"
	#define STR0008 "Abr"
	#define STR0009 "May"
	#define STR0010 "JUN"
	#define STR0011 "Jul"
	#define STR0012 "Ago"
	#define STR0013 "Set"
	#define STR0014 "Oct"
	#define STR0015 "Nov"
	#define STR0016 "Dic"
	#define STR0017 "ANULADO POR EL OPERADOR"
	#define STR0018 "Centro Costo: "
	#define STR0019 "OBSERVACIONES:"
	#define STR0020 "SOLICITUDES RESERVADAS :"
	#define STR0021 "No hay solicitudes reservados de este item."
	#define STR0022 "Orden de        Producto a ser         Inicio          Cantidad      |     Orden de        Producto a ser         Inicio          Cantidad      |     Orden de        Producto a ser         Inicio          Cantidad      |"
	#define STR0023 "Produccion      producido              Previsto        Necesaria     |     Produccion      producido              Previsto        Necesaria     |     Produccion      producido              Previsto        Necesaria     |"
	#define STR0024 "CONSUMO DE LOS ULTIMOS 12 MESES:"
	#define STR0025 "No hay registro de consumo anterior de este item."
	#define STR0026 " Promedio C"
	#define STR0027 "ULTIMOS PEDIDOS:"
	#define STR0028 "No hay pedidos en el archivo de este item. "
	#define STR0029 "Numero It Codigo de Proveedor  Tienda Nombre                                  Cantidad     Und.Medida   Vlr.Unitario    Valor Total    Emision       Necesidad      Plazo  Condicion   Ctd. Entregada   Saldo Res.   Eli.  |"
	#define STR0030 "PROVEEDORES :"
	#define STR0031 "No existen proveedores en el archivo para este item. "
	#define STR0032 "Codigo Suc Nombre                       Telefono        Contacto   FAX             Ul.Compr   Municipio       Pv Rie Cod. en Provee."
	#define STR0033 "Codigo Suc Nombre                       Telefono        Contacto   FAX             Ul.Compr   Municipio       Pv Rie Cod. en Provee."
	#define STR0034 "Codigo Alternativo : "
	#define STR0035 "Saldo del Alternativo :"
	#define STR0036 "No hay "
	#define STR0037 "|  C O M P E T I D O R E S                    | ENTREGA         | OBSERVACIONES                      | COND.PAGO        |  CONTACTO        |CANTIDAD        |  PRECIO UNITARIO            | IPI     |     VALOR            |"
	#define STR0038 "|                 REQUIRENTE                                                                                 |                    AUTORIZANTE                                                                              |"
	#define STR0039 "IT   CODIGO PRODUCTO  D  E  S  C  R  I  P  C  I  O  N            SALDO          PUNTO DE             SALDO      UNIDAD        DEPOSITO            CANT.POR       ULTIMO PRECIO        LEAD        FECHA DE LA     FECHA PARA"
	#define STR0040 "                                                                ACTUAL            PEDIDO         SOLICITUD      MEDIDA                            EMBALAJE           DE COMPRA        TIME        NECESIDAD       COMPRAR   "
	#define STR0041 "Codigo               Neg. RAZON SOCIAL Telefono       Contacto    Fax             Ult.Compr.  Municipio      Pr Rie Cod. en Proveed"
	#define STR0042 "Codigo Ng Nombre     Neg. Razon Social Telefono        Contacto   Fax             Ul.Compr Municipio         Pr Rie Cod. en Proveed"
	#define STR0043 "Numero "
	#define STR0044 "Numero It Codigo de Proveedor  Tiend Nombre                                   Cantidad     Und.Medida     Vlr.Unitario    Valor Total  Emision       Necesidad      Plazo  Condicion   Ctd. Entregada   Saldo Res.   Eli.  |"
	#define STR0045 "a.Emision "
	#define STR0046 "¡¡¡Actualizar SIGACUS.PRW !!!"
	#define STR0047 "¡¡¡Actualizar SIGACUSA.PRX !!!"
	#define STR0048 "¡¡¡Actualizar SIGACUSB.PRX !!!"
	#define STR0049 "Descripcion"
	#define STR0050 "Punto Pedido"
	#define STR0051 "Saldo de la SC"
	#define STR0052 "Lead Time"
	#define STR0053 "Fecha Necesidad"
	#define STR0054 "Fecha para Comprar"
	#define STR0055 "Orden de Producion"
	#define STR0056 "Producto por Producir"
	#define STR0057 "Inicio Previsto"
	#define STR0058 "Cantidad Necesaria"
	#define STR0059 "Plz.Dias"
	#define STR0060 "Saldo Res."
	#define STR0061 "Eli."
	#define STR0062 "No"
	#define STR0063 "Si"
#else
	#ifdef ENGLISH
		#define STR0001 "Print registered Purchase Requisitions"
		#define STR0002 "Purchase Requisition"
		#define STR0003 "Z.Form "
		#define STR0004 "Management"
		#define STR0005 "Jan"
		#define STR0006 "Feb"
		#define STR0007 "Mar"
		#define STR0008 "Apr"
		#define STR0009 "May"
		#define STR0010 "Jun"
		#define STR0011 "Jul"
		#define STR0012 "Aug"
		#define STR0013 "Sep"
		#define STR0014 "Oct"
		#define STR0015 "Nov"
		#define STR0016 "Dec"
		#define STR0017 "CANCELLED BY THE OPERATOR"
		#define STR0018 "Cost Center "
		#define STR0019 "NOTE:"
		#define STR0020 "ALLOCATED REQUISITIONS:"
		#define STR0021 "There are no allocated requisitions for this item."
		#define STR0022 "Production      Product to             Estimated       Demanded      |     Production      Product to             Estimated       Demanded      |     Production      Product to             Estimated       Demanded      |"
		#define STR0023 "Order           process                Start           Quantity      |     Order           process                Start           Quantity      |     Order           process                Start           Quantity      |"
		#define STR0024 "CONSUMPT.OF 12 LAST MONTHS:"
		#define STR0025 "No records of previous consumption were found for this Item."
		#define STR0026 "  Average C"
		#define STR0027 "LAST ORDERS:"
		#define STR0028 "There are no orders registered for this Item."
		#define STR0029 "Number It   Supplier Code        Unit  Name                                   Quantity     Un.of Mea.   Unit Value      Total Value    Issue Dt.     Necessity      Term   Condition   Qtty Delivered   Resid.Bal.   Del.  |"
		#define STR0030 "SUPPLIERS:"
		#define STR0031 "There are no Suppliers registered for this Item."
		#define STR0032 "Code   Un Name                         Telephone       Contact    Fax             Last Purch.   City         St Ris   Cod. at Suppl."
		#define STR0033 "Code   Un Name                         Telephone       Contact    Fax             Lst Purch. City            St Ris  Cod. at Suppl."
		#define STR0034 "Alternative Code: "
		#define STR0035 "Balance of the Alternative"
		#define STR0036 "There are no"
		#define STR0037 "|  C O N C U R R E N C E S                    | DELIVERY        | OBSERVATIONS                       | PAYMENT TERMS    |  CONTACT         |QUANTITY        |  UNIT PRICE                 | IPI     |     VALUE            |"
		#define STR0038 "|                 REQUESTER                                                                                  |                    APPROVED BY                                                                              |"
		#define STR0039 "IT   CODE   PRODUCT   D  E  S  C  R  I  P  T  I  O  N          CURRENT          POINT OF       REQUISITION      UNIT OF      WAREHOUSE            QTTY. BY       LAST PURCHASE        LEAD        NECESSITY       DATE TO  "
		#define STR0040 "                                                               BALANCE          ORDER           BALANCE         MEASUR.                            PACKAGE           PRICE            TIME           DATE         PURCHASE "
		#define STR0041 "Code                 Un.  Company Name Phone           Contact    Fax             Lst.Purc.   City           St Ris Code at Supplier"
		#define STR0042 "Code   Un Name       Unit Company Name   Phone           Contact    Fax             Lst.Pur. City            St Ris Code at Supplier"
		#define STR0043 "Number "
		#define STR0044 "Number Item Supplier Code        Unit  Name                                   Quantity     Un.of Mea.       Unit Value    Total Value  Issue Dt.     Necessity      Term   Condition   Qtty Delivered   Resid.Bal.   Del.  |"
		#define STR0045 "to Issue  "
		#define STR0046 "Atualizar SIGACUS.PRW !!!"
		#define STR0047 "Atualizar SIGACUSA.PRX !!!"
		#define STR0048 "Atualizar SIGACUSB.PRX !!!"
		#define STR0049 "Descricao"
		#define STR0050 "Ponto Pedido"
		#define STR0051 "Saldo da SC"
		#define STR0052 "Lead Time"
		#define STR0053 "Data Necessidade"
		#define STR0054 "Data para Comprar"
		#define STR0055 "Ordem de Producao"
		#define STR0056 "Produto a Ser Produzido"
		#define STR0057 "Inicio Previsto"
		#define STR0058 "Quantidade Necessaria"
		#define STR0059 "Prz.Dias"
		#define STR0060 "Saldo Res."
		#define STR0061 "Eli."
		#define STR0062 "Nao"
		#define STR0063 "Sim"
	#else
		#define STR0001 "Emissao das solicitacoes de compras cadastradas"
		#define STR0002 "Solicitacao de Compra"
		#define STR0003 "Zebrado"
		#define STR0004 "Administracao"
		#define STR0005 "Jan"
		#define STR0006 "Fev"
		#define STR0007 "Mar"
		#define STR0008 "Abr"
		#define STR0009 "Mai"
		#define STR0010 "Jun"
		#define STR0011 "Jul"
		#define STR0012 "Ago"
		#define STR0013 "Set"
		#define STR0014 "Out"
		#define STR0015 "Nov"
		#define STR0016 "Dez"
		#define STR0017 "CANCELADO PELO OPERADOR"
		#define STR0018 "  C.Custo : "
		#define STR0019 "OBSERVACOES:"
		#define STR0020 "REQUISICOES EMPENHADAS:"
		#define STR0021 "Nao existem requisicoes empenhadas deste item."
		#define STR0022 "Ordem de        Produto a ser          Inicio          Quantidade    |     Ordem de        Produto a ser          Inicio          Quantidade    |     Ordem de        Produto a ser          Inicio          Quantidade    |"
		#define STR0023 "Producao        produzido              Previsto        Necessaria    |     Producao        produzido              Previsto        Necessaria    |     Producao        produzido              Previsto        Necessaria    |"
		#define STR0024 "CONSUMO DOS ULTIMOS 12 MESES:"
		#define STR0025 "Nao existe registro de consumo anterior deste item."
		#define STR0026 "    Media C"
		#define STR0027 "ULTIMOS PEDIDOS:"
		#define STR0028 "Nao existem pedidos cadastrados para este item."
		#define STR0029 "Numero Item Codigo do Fornecedor Loja  Nome                                   Quantidade   Und.Medida   Vlr.Unitario    Valor Total    Emissao       Necessidade    Prazo  Condicao    Qtde Entregue    Saldo Res.   Eli.  |"
		#define STR0030 "FORNECEDORES:"
		#define STR0031 "Nao existem fornecedores cadastrados para este item."
		#define STR0032 "Codigo Lj Nome                         Telefone        Contato    Fax             Ul.Compr   Municipio       UF Ris  Cod. no Fornec."
		#define STR0033 "Codigo Lj Nome                         Telefone        Contato    Fax             Ul.Compr   Municipio       UF Ris  Cod. no Fornec."
		#define STR0034 "Codigo Alternativo : "
		#define STR0035 "Saldo do Alternativo :"
		#define STR0036 "Nao ha'"
		#define STR0037 "| C O N C O R R E N C I A S                   | ENTREGA         | OBSERVACOES                        | COND.PGTO        | CONTATO          | QUANTIDADE     | PRECO UNITARIO              | IPI     | VALOR                |"
		#define STR0038 "|                 REQUISITANTE                                                                               |                    AUTORIZANTE                                                                              |"
		#define STR0039 "ITEM CODIGO PRODUTO   D  E  S  C  R  I  C  A  O                  SALDO          PONTO DE          SALDO DA      UNIDADE       ARMAZEM            QUANT.POR        ULTIMO PRECO        LEAD        DATA DA         DATA PARA "
		#define STR0040 "                                                                 ATUAL            PEDIDO       SOLICITACAO      MEDIDA                           EMBALAGEM           DE COMPRA        TIME        NECESSIDADE      COMPRAR  "
		#define STR0041 "Codigo               Lj.  RAZAO SOCIAL Telefone        Contato    Fax             Ult.Compr.  Municipio      UF Ris Cod. no Fornec."
		#define STR0042 "Codigo Lj Nome       Loja Razao Social   Telefone        Contato    Fax             Ul.Compr Municipio       UF Ris Cod. no Fornec."
		#define STR0043 "Numero "
		#define STR0044 "Numero Item Codigo do Fornecedor Loja  Nome                                   Quantidade   Und.Medida     Vlr.Unitario    Valor Total  Emissao       Necessidade    Prazo  Condicao    Qtde Entregue    Saldo Res.   Eli.  |"
		#define STR0045 "a.Emissao "
		#define STR0046 "Atualizar SIGACUS.PRW !!!"
		#define STR0047 "Atualizar SIGACUSA.PRX !!!"
		#define STR0048 "Atualizar SIGACUSB.PRX !!!"
		#define STR0049 "Descricao"
		#define STR0050 "Ponto Pedido"
		#define STR0051 "Saldo da SC"
		#define STR0052 "Lead Time"
		#define STR0053 "Data Necessidade"
		#define STR0054 "Data para Comprar"
		#define STR0055 "Ordem de Producao"
		#define STR0056 "Produto a Ser Produzido"
		#define STR0057 "Inicio Previsto"
		#define STR0058 "Quantidade Necessaria"
		#define STR0059 "Prz.Dias"
		#define STR0060 "Saldo Res."
		#define STR0061 "Eli."
		#define STR0062 "Nao"
		#define STR0063 "Sim"
	#endif
#endif
